bcrypt added, login IF dried
Zed-CSP/codeConnoisseurs pull request #53
Opened 2023-05-18 00:58 UTC by Zed-CSP

added bcrypt to login api POST, dried multiple if statements.

2023-05-18 01:10 UTC, Zed-CSP commented on routes/api/userRoutes.js
> -    const validPassword = await userData.checkPassword(req.body.password);
modded and moved to line 7, possible dependency issue?

2023-05-19 01:47 UTC, rileydoneil requested changes
Change some things?

2023-05-19 01:50 UTC, Zed-CSP reviewed
fixed

2023-05-19 01:53 UTC, rileydoneil approved these changes

2023-05-19 01:53 UTC, merged